### ISSUE TITLE
Software renderer redesign for 0.15.0

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#223]
The existing software renderer is a naive 2.5D ray caster and retains several poor design choices from the past few years. Although it has a couple optimizations like multi-threading and per-pixel-column occlusion culling, it was meant only for prototyping new features. I am rewriting it for 0.15.0 so it is actually decent (more importantly: _optimizable_) and can match Arena's appearance more closely with 8-bit palette colors instead of true color.

**Part 1**
- Scrap 2.5D ray caster, salvaging important functions
- Implement scene graph which feeds the renderer geometry and lights and keeps gameplay details (voxels/entities/sky/etc.) away. The renderer stores only frame buffers and allocated textures; it does not own geometry
- Implement 3D triangle rasterization (projection, clipping, barycentric coordinates, debug RGB colors, perspective correctness)
- Implement all pixel shaders using 8-bit textures and light tables, supporting material types (i.e. opaque/alpha-tested/ghost)
- Don't need optimization or features like dithering or multi-threading in bulk yet
- Some color/palette bugs are okay

**Part 2**
- Prepare for 0.15.0 release, fix bugs
- All features in to look identical to Arena (i.e. dithering)
- More scene graph optimizations (antiportal occlusion culling, multi-threading)
- See how close to 2160p 60 fps we can get

Branch naming convention: `sw-renderer-redesign-part-#`

**Comment by afritz1** [comment]
Revised roadmap as of 8/18/2022.

**Part 1**
- [x] Implement 3D triangle rasterization (projection, clipping, barycentric coordinates, perspective correctness)
- [x] Implement vertex buffers, attribute buffers, and index buffers
- [x] Implement 8-bit texturing
- [ ] Implement basic scene graph which feeds the renderer draw calls every frame for visible geometry
- [ ] Implement one pixel shader for all geometry just to get everything on-screen
- [ ] Various engine design clean-ups to support renderer development as needed (scene management, etc.)
- [ ] Get to a "geometry-complete" state, meaning all voxels, entities, sky objects, and particles are appearing in-world

**Part 2**
- [ ] Implement pixel shader per material (opaque, alpha-tested, ghost, chasm wall, etc.)
- [ ] Implement lights using light tables and basic forward rendering, supporting up to 8 lights per draw call
- [ ] Get appearance to be nearly identical to Arena while supporting any screen resolution

**Part 3**
- [ ] Implement quadtree acceleration structure for faster frustum culling
- [ ] Better ordering of draw calls for performance (opaque front-to-back, alpha-tested back-to-front, etc.)
- [ ] Multi-threading
- [ ] (optional) Overdraw reduction (tile-based occlusion culling)
- [ ] (optional) Avoid clearing frame buffer every frame
- [ ] Prepare for 0.15.0 release, fix any big remaining bugs

**Comment by afritz1** [comment]
#252 is a big enough issue with rain/snow that it should be considered a blocker for finishing part 3.

**Comment by afritz1** [comment]
Done with #252.

**Comment by afritz1** [comment]
Going to skip harder optimizations like occlusion culling and just optimize the rasterizer and shaders a more conventional way with fewer special cases/algorithms/etc..

Ideally opaque meshes would draw front to back without depth reads and then sky would draw after it with a `depth < INFINITY` check, but that's too hard to implement, so instead going to draw sky first and then everything else after it.

**Comment by afritz1** [comment]
Deciding how to handle tiled rendering with puddles and ghosts, because these two shaders have to read from the frame buffer. I think trying to do multi-pass shading is a good idea instead of coming up with a complex tile scheduler to keep threads from blocking on unfinished tiles.

**Comment by afritz1** [comment]
Added multi-threading today but performance is still poor even with very high threads. I think the binning design will need to change so they store much more work for each thread, instead of needing threads to synchronize every 8 or so draw calls.

**Comment by afritz1** [comment]
Finally fixed the deadlock and was able to get this to a finish line. Performance is okay at 1080p60 on a high end CPU but could be better. I think batching is much more important than adding voxel occlusion for reducing draw calls.
